identifier = "com.exitclear.backend"
entrypoint = ["bash", "-c", "python3 /app/main.py --source oak"]
app_version = "0.1.0"

prepare_container = [
    { type = "COPY", source = "./requirements.txt", target = "./requirements.txt" },
    { type = "RUN", command = "python3.12 -m pip install -r /app/requirements.txt --break-system-packages" }
]

[env]
PYTHONUNBUFFERED = "1"

[base_image]
api_url = "https://registry-1.docker.io"
service = "registry.docker.io"
oauth_url = "https://auth.docker.io/token"
auth_type = "repository"
auth_name = "luxonis/oakapp-base"
image_name = "luxonis/oakapp-base"
image_tag = "1.2.5"
